# __SETTINGS FILE__ #

# __IMPORTS__#
import pygame as pg
from pygame.locals import *
import random, sys

# __WINDOW SETTINGS__ #
TITLE = 'MEMORY PUZZLE'
FPS = 30  # GAME SPEED
WIDTH = 640
HEIGHT = 480
RES = (WIDTH, HEIGHT)  # WINDOW RESOLUTION

# __GAME SETTINGS__ #
REVEALSPEED = 8
BOXSIZE = 40
GAPSIZE = 10
BOARDWIDTH = 10
BOARDHEIGHT = 8
# BOARDWIDTH * BOARDHEIGHT MUST BE EVEN
XMARGIN = int((WIDTH - (BOARDWIDTH * (BOXSIZE + GAPSIZE))) / 2)
YMARGIN = int((HEIGHT - (BOARDHEIGHT * (BOXSIZE + GAPSIZE))) / 2)

# __COLORS__ #
# _____ R _ G _ B _ #
WHITE = (255, 255, 255)
GRAY = (100, 100, 100)
RED = (255, 0, 0)
DARKRED = (155, 0, 0)
GREEN = (0, 255, 0)
YELLOW = (255, 255, 0)
ORANGE = (255, 128, 0)
PURPLE = (255, 0, 255)
BLUE = (0, 0, 255)
CYAN = (0, 255, 255)
NAVYBLUE = (60, 60, 100)

BGCOLOR = NAVYBLUE
LIGHTBGCOLOR = GRAY
BOXCOLOR = WHITE
HIGHLIGHTCOLOR = BLUE

# Color List
COLORS = [RED, DARKRED, GREEN, BLUE, YELLOW, ORANGE, PURPLE, CYAN, WHITE]

# __SHAPES__ #
DONUT = 'donut'
SQUARE = 'square'
DIAMOND = 'diamond'
LINES = 'lines'
OVAL = 'oval'

# Shape List
SHAPES = [DONUT, SQUARE, DIAMOND, LINES, OVAL]


